$ErrorActionPreference = 'Stop'

$Root = $PSScriptRoot
$ConfigDir = Join-Path $Root 'config'
$ConfigPath = Join-Path $ConfigDir 'team.ps1'
$SecretPath = Join-Path $ConfigDir 'api-key.dpapi'

Write-Host ''
Write-Host '========================================' -ForegroundColor Cyan
Write-Host ' Configure DWB Serena Tunnel' -ForegroundColor Cyan
Write-Host '========================================' -ForegroundColor Cyan
Write-Host ''

$TunnelId = Read-Host 'Tunnel ID (tunnel_...)'
if ([string]::IsNullOrWhiteSpace($TunnelId) -or $TunnelId -cnotmatch '^tunnel_[0-9a-f]{32}$') {
    throw 'Invalid Tunnel ID. Expected tunnel_ followed by 32 lowercase hexadecimal characters.'
}

$SecureKey = Read-Host 'OpenAI Runtime API key' -AsSecureString
if ($SecureKey.Length -eq 0) {
    throw 'API key cannot be empty.'
}

New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null

$TunnelEscaped = $TunnelId.Replace("'", "''")
$ConfigContent = @"
# DWB Serena Tunnel - local configuration
# Generated by Configure.cmd.
# This file contains the Tunnel ID only. The API key is stored separately using Windows DPAPI.

`$TunnelId = '$TunnelEscaped'
"@
Set-Content -Path $ConfigPath -Value $ConfigContent -Encoding utf8

# ConvertFrom-SecureString without an explicit key uses Windows DPAPI.
# The encrypted value can only be decrypted by the same Windows user on the same account context.
$EncryptedKey = ConvertFrom-SecureString -SecureString $SecureKey
Set-Content -Path $SecretPath -Value $EncryptedKey -Encoding ascii

Write-Host ''
Write-Host "Tunnel configuration saved: $ConfigPath" -ForegroundColor Green
Write-Host "API key encrypted with Windows DPAPI: $SecretPath" -ForegroundColor Green
Write-Host ''
Write-Host 'Next: run Start.cmd' -ForegroundColor Cyan
Write-Host ''
